"""Add bot_name column to User

Revision ID: 89ae8409703c
Revises: 2d13bb6e87f9
Create Date: 2024-01-27 12:13:12.132199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ae8409703c'
down_revision = '2d13bb6e87f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('membership',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Free'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('membership',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'Free'"))
        batch_op.drop_column('bot_name')

    # ### end Alembic commands ###
