"""Add bot_name, bot_token, and bot_public_key columns to User

Revision ID: ec109a4d3faf
Revises: 89ae8409703c
Create Date: 2024-01-27 12:26:17.578224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec109a4d3faf'
down_revision = '89ae8409703c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bot_public_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bot_public_key')
        batch_op.drop_column('bot_token')

    # ### end Alembic commands ###
